### ISSUE TITLE
运行报错mingw32/bin/ld.exe: cannot find -ltest

### ISSUE THREAD

**Issue by mileswild** [CaiquanLiu/GTest-CLion-example#1]
[ 50%] Linking CXX executable GoodCodeEddy.exe
c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: cannot find -ltest
c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: cannot find -lpthread
collect2.exe: error: ld returned 1 exit status
CMakeFiles\GoodCodeEddy.dir\build.make:96: recipe for target 'GoodCodeEddy.exe' failed
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/GoodCodeEddy.dir/all' failed
CMakeFiles\Makefile2:78: recipe for target 'CMakeFiles/GoodCodeEddy.dir/rule' failed
Makefile:117: recipe for target 'GoodCodeEddy' failed
mingw32-make.exe[3]: *** [GoodCodeEddy.exe] Error 1
mingw32-make.exe[2]: *** [CMakeFiles/GoodCodeEddy.dir/all] Error 2
mingw32-make.exe[1]: *** [CMakeFiles/GoodCodeEddy.dir/rule] Error 2
mingw32-make.exe: *** [GoodCodeEddy] Error 2

**Comment by CaiquanLiu** [comment]
GTest-CLion-example是在linux（Ubuntu）环境测试使用的，Windows环境暂时没有测试
